CREATE TABLE "commute_events" (
	"id" serial PRIMARY KEY NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"event_name" text NOT NULL,
	"role" text,
	"step" integer,
	"poster_source" text,
	"anonymous_visitor_id" text,
	"browser_session_id" text,
	"dedupe_key" text,
	CONSTRAINT "commute_events_dedupe_key_unique" UNIQUE("dedupe_key")
);
--> statement-breakpoint
CREATE TABLE "commute_poster_registry" (
	"poster_id" text PRIMARY KEY NOT NULL,
	"location_name" text,
	"latitude" double precision,
	"longitude" double precision,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "commute_responses" (
	"id" serial PRIMARY KEY NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"role" text NOT NULL,
	"survey_version" text DEFAULT 'v1' NOT NULL,
	"lives_in_sage_creek" boolean NOT NULL,
	"lives_outside_sage_creek" boolean DEFAULT false NOT NULL,
	"neighborhood" text,
	"student_status" text DEFAULT 'legacy' NOT NULL,
	"is_uofm_student" boolean NOT NULL,
	"schedule" jsonb NOT NULL,
	"weekly_trip_count" integer,
	"arrival_flexibility" text NOT NULL,
	"departure_flexibility" text NOT NULL,
	"ride_direction" text NOT NULL,
	"max_detour" text,
	"seats" text,
	"max_pickup_walk" text,
	"current_transport_method" text,
	"current_commute_duration" text,
	"minimum_monthly_compensation" text,
	"maximum_monthly_willingness_to_pay" text,
	"driver_rate_cents" integer,
	"driver_rate_selection" text,
	"rider_price_cents" integer,
	"rider_price_selection" text,
	"schedule_change_frequency" text NOT NULL,
	"dealbreaker" text NOT NULL,
	"dealbreaker_other" text,
	"final_concern" text,
	"final_concern_other" text,
	"intent_level" text NOT NULL,
	"first_name" text,
	"email" text,
	"phone" text,
	"contact_method" text DEFAULT 'none' NOT NULL,
	"contact_permission" boolean DEFAULT false NOT NULL,
	"prefers_text" boolean DEFAULT false NOT NULL,
	"utm_source" text,
	"utm_medium" text,
	"utm_campaign" text,
	"referrer" text,
	"poster_source" text,
	"submission_id" text,
	CONSTRAINT "commute_responses_submission_id_unique" UNIQUE("submission_id")
);
